född = int(input("Hej, vilket år föddes du?"))
år = int(input("Vilket år är det nu?"))
månad = int(input("Vilket månad föddes du? Kom ihåg att skriva ett nummer mellan 1 och 12."))
månad1 = (int(månad)/12)
år1 = (int(år)-int(född))
år2 = (år1) + (månad1)
månad3 = int(input("Vilken månad är det just nu? Kom ihåg att skriva ett nummer mellan 1 och 12."))
månad4 = (int(månad3)/12)
år3 = int(månad4) + (år2)
dag1 = int(input("Vilken dag på månaden är det just nu? Kom ihåg att skriva ett nummer mellan 1 och 31."))
dag2 = (int(dag1)/365)
år4 = (år3) + (dag2)
timme1 = int(input("Vilken timme är det just nu? Kom ihåg att skriva ett nummer mellan 1 och 24."))
timme2 = (int(timme1) / 8760)
år5 = (timme2) + (år4)
minut1 = int(input("Vilken minut är det just nu? Kom ihåg att skriva ett nummer mellan 1 och 59."))
minut2 = (int(minut1) / 525600)
år6 = (minut2) + (år5)
sekund1 = int(input("Vilken sekund är det just nu? Kom ihåg att skriva ett nummer mellan 1 och 59."))
sekund2 = (int(sekund1) /31536000)
år7 = (sekund2 + år6)
år8 = (år7) * 31536000
ungefärmånad = int(år7) * 12
ungefärdagar1 = år7 * 365 
ungefärdagar2 = int(ungefärdagar1)
ungefärtimmar1 = år7 * 8760
ungefärtimmar2 = int(ungefärtimmar1)
ungefärminuter1 = år7 * 525600
ungefärminuter2 = int(ungefärminuter1)
print ("-")
print ("-")
print ("-")
print ("-")
print ("-")
print ("-")
print ("-")
print ("Du är just nu:")
print (int(år1) , "år gammal")
print (ungefärmånad , "månader gammal")
print (ungefärdagar2 , "dagar gammal")
print (ungefärtimmar2 , "timmar gammal")
print (ungefärminuter2 , "minuter gammal")
print ("-")
print ("Du är just nu ungefär" , int(år8) , "sekunder gammal.")
print ("^-^-^-^-^-^")
print ("Du är just nu exakt" , år8 , "sekunder gammal.")
print ("-")
print ("Tack för mig! :)")