namn1age = int(16)
Namn1 = ("Josh")
print ("Vällkommen")
print ("Detta program ägs av Josh")
namn2 = input("Vad heter du?")
namn2age = int(input("Hur gammal är du?"))
totalage = int(namn1age) + int(namn2age)
print ("Din ålder och Josh ålder är tillsammans:" , totalage )
print ("-")
print ("Du kan nu forsätta...")